import { StyleSheet } from 'react-native';

export const createThemedStyles = (colors: any, isDarkMode: boolean = false) => StyleSheet.create({
  scrollView: {
    flex: 1,
    backgroundColor: isDarkMode ? '#111827' : '#ffffff',
  },
  container: {
    paddingBottom: 40,
  },
  headerContainer: {
    marginBottom: 8,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 12,
    color: isDarkMode ? '#ffffff' : '#1a1a1a',
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  detailSection: {
    marginVertical: 12,
    backgroundColor: isDarkMode ? '#2a2a2a' : '#e8e8e8',
    borderRadius: 16,
    padding: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: isDarkMode ? 0.3 : 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  timezoneInfo: {
    marginVertical: 8,
    padding: 16,
    backgroundColor: isDarkMode ? '#2a2a2a' : '#e8e8e8',
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: isDarkMode ? 0.3 : 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  error: {
    color: '#ff4444',
    fontSize: 18,
    textAlign: 'center',
    fontWeight: '600',
  },
  controlContainer: {
    marginVertical: 12,
  },
  resultContainer: {
    marginTop: 20,
    padding: 18,
    backgroundColor: isDarkMode ? '#2a2a2a' : '#e8e8e8',
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: isDarkMode ? 0.3 : 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  severityText: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 8,
    color: isDarkMode ? '#ffffff' : '#1a1a1a',
  },
  recommendationsContainer: {
    marginTop: 12,
  },
  recommendationsTitle: {
    fontWeight: 'bold',
    marginBottom: 8,
    fontSize: 16,
    color: isDarkMode ? '#ffffff' : '#1a1a1a',
  },
  subResultContainer: {
    marginTop: 12,
    padding: 16,
    backgroundColor: isDarkMode ? '#404040' : '#d0d0d0',
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: isDarkMode ? 0.2 : 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  subTitle: {
    fontWeight: 'bold',
    marginBottom: 8,
    fontSize: 16,
    color: isDarkMode ? '#ffffff' : '#1a1a1a',
  },
  loader: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: isDarkMode ? 'rgba(26, 26, 26, 0.9)' : 'rgba(245, 245, 245, 0.9)',
    zIndex: 1000,
  },
  saveButton: {
    backgroundColor: isDarkMode ? '#1f2937' : '#f3f4f6',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: 'center',
    marginHorizontal: 20,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: isDarkMode ? '#374151' : '#e5e7eb',
  },
  saveButtonText: {
    color: isDarkMode ? '#9ca3af' : '#6b7280',
    fontWeight: '600',
    fontSize: 15,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: isDarkMode ? '#111827' : '#ffffff',
  },
});

export default createThemedStyles;
