import { StyleSheet } from 'react-native';

export const createLocalStyles = (colors: any, isDarkMode: boolean = false) => StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'flex-end',
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modal: {
    backgroundColor: isDarkMode ? '#2a2a2a' : '#e8e8e8',
    padding: 20,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    flexDirection: 'row',
    justifyContent: 'space-around',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: isDarkMode ? 0.3 : 0.1,
    shadowRadius: 4,
    elevation: 5,
  },
  modalView: {
    backgroundColor: isDarkMode ? '#2a2a2a' : '#e8e8e8',
    borderRadius: 20,
    padding: 24,
    width: '85%',
    maxWidth: 400,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: isDarkMode ? 0.4 : 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 20,
    textAlign: 'center',
    color: isDarkMode ? '#ffffff' : '#1a1a1a',
  },
  iconButton: {
    alignItems: 'center',
    padding: 16,
    backgroundColor: isDarkMode ? '#404040' : '#d0d0d0',
    borderRadius: 16,
    minWidth: 100,
  },
  iconLabel: {
    marginTop: 8,
    fontSize: 14,
    color: isDarkMode ? '#ffffff' : '#1a1a1a',
    textAlign: 'center',
    fontWeight: '600',
  },
  button: {
    backgroundColor: isDarkMode ? '#404040' : '#d0d0d0',
    padding: 16,
    borderRadius: 12,
    marginVertical: 8,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: isDarkMode ? 0.3 : 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  buttonText: {
    fontSize: 16,
    fontWeight: '600',
    color: isDarkMode ? '#ffffff' : '#1a1a1a',
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '600',
    marginTop: 12,
    marginBottom: 8,
    color: isDarkMode ? '#ffffff' : '#1a1a1a',
  },
  input: {
    borderWidth: 1,
    borderColor: isDarkMode ? '#404040' : '#d0d0d0',
    borderRadius: 12,
    padding: 14,
    fontSize: 16,
    marginBottom: 12,
    backgroundColor: isDarkMode ? '#1a1a1a' : '#ffffff',
    color: isDarkMode ? '#ffffff' : '#1a1a1a',
  },
  errorText: {
    color: '#ff4444',
    marginBottom: 12,
    textAlign: 'center',
    fontSize: 14,
    fontWeight: '600',
  },
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 16,
    gap: 12,
  },
  cancelButton: {
    backgroundColor: isDarkMode ? '#404040' : '#d0d0d0',
    flex: 1,
  },
  submitButton: {
    backgroundColor: isDarkMode ? '#666666' : '#b0b0b0',
    flex: 1,
  },
  debugButton: {
    backgroundColor: isDarkMode ? '#404040' : '#d0d0d0',
    padding: 16,
    borderRadius: 12,
    marginVertical: 8,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  debugButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: isDarkMode ? '#ffffff' : '#1a1a1a',
  },
});

// Keep backward compatibility
const localStyles = createLocalStyles({}, false);
export default localStyles;