// services/calendarService.ts
import * as Calendar from 'expo-calendar';
import { Platform, Alert } from 'react-native';
import { SwitchingTimes } from '../utils/types';
import { Moment } from 'moment';

export interface CalendarEventResult {
  success: boolean;
  eventsCreated: number;
  message: string;
}

export interface Intervention {
  time: Moment;
  type: 'melatonin' | 'caffeine';
  dose: number;
}

/**
 * Request calendar permissions from the user
 */
async function requestCalendarPermissions(): Promise<boolean> {
  try {
    const { status } = await Calendar.requestCalendarPermissionsAsync();

    if (status !== 'granted') {
      Alert.alert(
        'Calendar Permission Required',
        'Please enable calendar access in your device settings to add switching times to your calendar.',
        [{ text: 'OK' }]
      );
      return false;
    }

    return true;
  } catch (error) {
    console.error('Error requesting calendar permissions:', error);
    Alert.alert('Error', 'Failed to request calendar permissions');
    return false;
  }
}

/**
 * Get or create the default calendar for the app
 */
async function getDefaultCalendar(): Promise<string | null> {
  try {
    const calendars = await Calendar.getCalendarsAsync(Calendar.EntityTypes.EVENT);

    // Try to find the primary calendar
    let defaultCalendar = calendars.find(
      cal => cal.allowsModifications && (cal.isPrimary || cal.title === 'Calendar')
    );

    // If no primary calendar, use the first writable one
    if (!defaultCalendar) {
      defaultCalendar = calendars.find(cal => cal.allowsModifications);
    }

    if (!defaultCalendar) {
      Alert.alert('Error', 'No writable calendar found on your device');
      return null;
    }

    return defaultCalendar.id;
  } catch (error) {
    console.error('Error getting default calendar:', error);
    Alert.alert('Error', 'Failed to access device calendar');
    return null;
  }
}

/**
 * Create calendar event for a switching time
 */
async function createSwitchingTimeEvent(
  calendarId: string,
  switchingPoint: { time: string; type: 'light' | 'dark' },
  flightNumber: string
): Promise<boolean> {
  try {
    const startDate = new Date(switchingPoint.time);
    // Make events 1 hour long by default
    const endDate = new Date(startDate.getTime() + 60 * 60 * 1000);

    const isLightExposure = switchingPoint.type === 'light';

    const eventDetails = {
      title: isLightExposure ? '☀️ Light Exposure - JetShifter' : '🌙 Avoid Light - JetShifter',
      notes: isLightExposure
        ? `Get bright light exposure now to help adjust your circadian rhythm.\n\nFlight: ${flightNumber}\n\nGenerated by JetShifter`
        : `Avoid bright light now. Wear sunglasses or stay in dim lighting to help adjust your circadian rhythm.\n\nFlight: ${flightNumber}\n\nGenerated by JetShifter`,
      startDate,
      endDate,
      timeZone: 'default',
      alarms: [
        { relativeOffset: 0 }, // Alarm at event time
        { relativeOffset: -15 }, // Reminder 15 minutes before
      ],
    };

    await Calendar.createEventAsync(calendarId, eventDetails);
    return true;
  } catch (error) {
    console.error('Error creating switching time event:', error);
    return false;
  }
}

/**
 * Create calendar event for an intervention (melatonin/caffeine)
 */
async function createInterventionEvent(
  calendarId: string,
  intervention: Intervention,
  flightNumber: string
): Promise<boolean> {
  try {
    const startDate = intervention.time.toDate();
    // Make intervention events 30 minutes long
    const endDate = new Date(startDate.getTime() + 30 * 60 * 1000);

    const isMelatonin = intervention.type === 'melatonin';

    const eventDetails = {
      title: isMelatonin ? '💊 Melatonin - JetShifter' : '☕ Caffeine - JetShifter',
      notes: isMelatonin
        ? `Take ${intervention.dose}mg melatonin to help adjust your circadian rhythm.\n\nFlight: ${flightNumber}\n\nGenerated by JetShifter`
        : `Have your coffee (${intervention.dose}mg caffeine) to maintain alertness.\n\nFlight: ${flightNumber}\n\nGenerated by JetShifter`,
      startDate,
      endDate,
      timeZone: 'default',
      alarms: [
        { relativeOffset: 0 }, // Alarm at event time
        { relativeOffset: -30 }, // Reminder 30 minutes before
      ],
    };

    await Calendar.createEventAsync(calendarId, eventDetails);
    return true;
  } catch (error) {
    console.error('Error creating intervention event:', error);
    return false;
  }
}

/**
 * Add all switching times and interventions to the device calendar
 */
export async function addSwitchingTimesToCalendar(
  switchingTimes: SwitchingTimes,
  flightNumber: string,
  interventions?: Intervention[]
): Promise<CalendarEventResult> {
  // Request permissions
  const hasPermission = await requestCalendarPermissions();
  if (!hasPermission) {
    return {
      success: false,
      eventsCreated: 0,
      message: 'Calendar permission denied',
    };
  }

  // Get the default calendar
  const calendarId = await getDefaultCalendar();
  if (!calendarId) {
    return {
      success: false,
      eventsCreated: 0,
      message: 'No writable calendar found',
    };
  }

  let eventsCreated = 0;
  let totalEvents = switchingTimes.switchingPoints.length + (interventions?.length || 0);

  // Create events for all switching points
  for (const switchingPoint of switchingTimes.switchingPoints) {
    const created = await createSwitchingTimeEvent(calendarId, switchingPoint, flightNumber);
    if (created) {
      eventsCreated++;
    }
  }

  // Create events for interventions (melatonin/caffeine) if provided
  if (interventions && interventions.length > 0) {
    for (const intervention of interventions) {
      const created = await createInterventionEvent(calendarId, intervention, flightNumber);
      if (created) {
        eventsCreated++;
      }
    }
  }

  if (eventsCreated === totalEvents) {
    return {
      success: true,
      eventsCreated,
      message: `Successfully added ${eventsCreated} events to your calendar`,
    };
  } else if (eventsCreated > 0) {
    return {
      success: true,
      eventsCreated,
      message: `Added ${eventsCreated} of ${totalEvents} events to your calendar`,
    };
  } else {
    return {
      success: false,
      eventsCreated: 0,
      message: 'Failed to create calendar events',
    };
  }
}

/**
 * Check if the app has calendar permissions
 */
export async function hasCalendarPermissions(): Promise<boolean> {
  try {
    const { status } = await Calendar.getCalendarPermissionsAsync();
    return status === 'granted';
  } catch (error) {
    console.error('Error checking calendar permissions:', error);
    return false;
  }
}
